[package]
name = "rust-ffi"
version = "0.1.0"
edition = "2021"

[lib]
path = "rust-src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0"
egui = "0.29"
egui_extras = "0.29"
indexmap = { version = "2.6", features = ["serde"] }
opener = "0.7"
parking_lot = "0.12"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
strum = "0.26"
strum_macros = "0.26"
toml = { version = "0.8", features = ["preserve_order"] }

[build-dependencies]
bindgen = "0.70"